app/__init__.py
from flask import Flask
from flask import render_template, redirect, url_for
from flask_bootstrap3 import Bootstrap
from .views.jgq import jgq
from .views.cbfd import cbfd
from .views.rules import rules
import linecache
import random
import os

app = Flask(__name__)
app.config.from_object('config')

bootstrap = Bootstrap(app)
app.register_blueprint(jgq)
app.register_blueprint(cbfd)
app.register_blueprint(rules)


#from . import indexview
@app.route('/')
def index():
    return redirect('/jgq')
    #return render_template('jgq.html')

@app.route('/about')
def about():
    print(os.getcwd())
    basedir = os.path.abspath(os.path.dirname(__file__))
    filename = basedir +'/skill.txt'
    with open(filename) as f:
        lines = f.readlines()
        random_num = random.randint(1,len(lines))
        string = linecache.getline(filename,random_num)
    return render_template('about.html',str = string)

app/views/cbfd.py
from flask import Blueprint, render_template

cbfd = Blueprint('cbfd', __name__, url_prefix='/cbfd')


@cbfd.route('/')
def index():
    user = 'test'
    return render_template('cbfd.html',user = user)

app/views/jgq.py
from flask import Blueprint, render_template, make_response, send_file, request
from werkzeug.utils import secure_filename
import os
import time
import base64

from ..form.jgqform import JgqForm
from ..utils.jgq_utils import calc,format_time, allowed_file, batch, is_right_file, get_time, format_form
import flask_excel as excel
import copy


jgq = Blueprint('jgq', __name__, url_prefix='/jgq')






export_data = []
data_flag = False


@jgq.route('/', methods = ['GET', 'POST'])
def index():
    form = JgqForm()
    return render_template('jgq.html', form = form)


#计算间隔期
@jgq.route('/calc', methods = ['GET', 'POST'])
def jgq_calc():
    str = None
    flag = False
    jgq = '2年'
    form = JgqForm()
    if form.validate_on_submit():
        form = format_form(form)
        if form:
            zuiming = form.zuiming.data
            yuanpanxingqi = int(form.yuanpanxingqi.data)
            chengbaodate = format_time(form.chengbaodate.data)
            qishishijian = format_time(form.qishishijian.data)
            shangcijxfd = int(form.shangcijxfd.data)
            jxqishishijian = format_time(form.jxqishishijian.data)
            ligong = int(form.ligong.data)
            zhongdaligong = int(form.zhongdaligong.data)

        #print(zuiming,yuanpanxingqi,chengbaodate,qishishijian,shangcijxfd,
        #      jxqishishijian,ligong,zhongdaligong)

            flag = calc(zuiming, yuanpanxingqi, chengbaodate, qishishijian, shangcijxfd,
             jxqishishijian, ligong, zhongdaligong)
        #print(flag)
            if flag:
                str = '服刑人员间隔期已过'
            else:
                str = '服刑人员间隔期未过，不能呈报减刑！'

            return render_template('jgq.html', form=form, str = str,flag = flag)
        else:
            form = JgqForm()
            flag = False
            str = '输入信息有误，请检查！'
            return render_template('jgq.html', form=form, str=str, flag=flag)


#下载模板
@jgq.route('/down_template',methods = ['GET'])
def download_template():
    filename = 'template.xls'
    response = make_response(send_file(filename))
    response.headers["Content-Disposition"] = "attachment; filename={0};".format(filename)
    return response

#下载批量计算后的文件
@jgq.route('/download_jgq',methods = ['GET'])
def download_jgq():
    global data_flag
    if data_flag:
        time_name = 'jian_ge_qi_'+get_time(time.time())
        #data_flag = False
        return excel.make_response_from_array(export_data, file_type="xls",file_name = time_name)
    else:
        file_str = '文件未上传，请上传文件！'
        data_flag = False
        return render_template('batch.html', str=file_str)



# 上传文件
@jgq.route('/api/upload', methods=['POST'], strict_slashes=False)
def api_upload():
    global export_data
    global data_flag
    file_str = '文件上传不成功，请重新上传！'

    file_upload = False
    form = JgqForm()
    file_dir = 'upload'
    template_name = 'batch'
    basedir = os.path.abspath(os.path.dirname(__file__))
    file_dir = os.path.join(basedir, 'upload')
    if not os.path.exists(file_dir):
        os.makedirs(file_dir)
    f = request.files['myfile']  # 从表单的file字段获取文件，myfile为该表单的name值
    if f and allowed_file(f.filename):  # 判断是否是允许上传的文件类型
        fname = secure_filename(f.filename)
        ext = fname.rsplit('.', 1)[1]  # 获取文件后缀
        unix_time = int(time.time())
        new_filename = str(unix_time) + '.' + ext  # 修改了上传的文件名
        f.save(os.path.join(file_dir, new_filename))  # 保存文件到upload目录
        token = base64.b64encode(new_filename.encode('ascii'))
        #f.save(os.path.join(file_dir, template_name))  # 保存文件到upload目录

        #print(token)
        file_str = '文件上传成功！'
        if is_right_file(file_dir+'/'+new_filename):
            file_upload = True
            data = batch(file_dir+'/'+new_filename)
            export_data = data
            data_flag = True
        else:
            file_str = '服刑人员信息填写不全或有误，请认真填写后上传！'
            data_flag = False
            data = []
        return render_template('batch.html', fileupload = file_upload, str = file_str,data = data)
        #return jsonify({"errno": 0, "errmsg": "上传成功", "token": str(token)})
    else:
        return render_template('batch.html', fileupload = file_upload, str = file_str)
        #return jsonify({"errno": 1001, "errmsg": "上传失败"})

app/views/rules.py
from flask import Blueprint






rules = Blueprint('rules', __name__, url_prefix='/rules')

app/templates/about.html
{% extends "header.html" %}
{% block page_navbar %}


{% endblock %}
{% block container %}
    <p><a class="btn btn-primary btn-lg" href="/jgq" role="button">返回工具集</a></p>
    <div class="jumbotron">
        <p>{{ str }}</p>
        <h4><p style="float: right">by 哈尔滨监狱 信息技术科 韩峰</p></h4>
    </div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}减刑辅助工具{% endblock %}

{% block navbar %}
<div class="navbar navbar-fixed-top">
  <!-- ... -->
</div>
{% block page_navbar %}
 {% endblock %}

{% endblock %}

{% block container%}
{% endblock %}

app/templates/batch.html
{% extends "header.html" %}
{% block page_navbar %}
    <div>
    <ul class="nav nav-tabs" role="tablist" id="myTab">
    <li role="presentation" class="active"><a href="/jgq" >减刑间隔期计算器</a></li>
    <li role="presentation" ><a href="/cbfd">呈报幅度建议工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑细则速查</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑摸底排查工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">常用问题集</a></li>
    </ul>
    </div>

{% endblock %}

{% block container%}
<div>
    <h3><span class="label label-primary">方法二：</span></h3>
    <div class="jumbotron">
        <h4>使用说明：</h4>
        <p>下载表格模板，按要求填写后上传，批量计算服刑人员呈报减刑间隔期是否符合</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('jgq.download_template') }}" role="button">下载表格模板</a></p>
    </div>
    <h4><span class="label label-primary">请选择文件,文件格式为xls、xlsx：</span></h4>
    <form id="form1" method="post" action="/jgq/api/upload" enctype="multipart/form-data">
    <div>
        <input id="File1" type="file" name="myfile"/>
        <button type="submit" class="btn btn-info">提交</button>
    </div>

    </form>
    {% if fileupload %}
        <h3><div class="alert alert-success" role="alert">{{ str }}</div></h3>
    {% else %}
        <h3><div class="alert alert-danger" role="alert">{{ str }}</div></h3>
    {% endif %}
</div>
<div class="panel panel-default">
<div class="panel-body">
<table class="table table-bordered" align="center" valign="middle">
   <caption ><h2>间隔期</h2></caption>
   <thead>
      <tr>

         <th>姓名</th>
         <th>罪名</th>
         <th>原判刑期</th>
         <th>呈报日期</th>
         <th>起始时间</th>
         <th>上次减刑幅度</th>
         <th>上次减刑起始时间</th>
          <th>立功</th>
         <th>重大立功</th>
         <th>是否符合间隔期</th>
      </tr>
   </thead>
   <tbody>
      <tr>
      {% for row in data%}

          {% if '已过' in row[9] %}
          <tr class="alert-success">
          {% else  %}
          <tr class="alert-danger">
          {% endif %}
          {% for one in row %}
              <td>{{ one }}</td>
          {% endfor %}
          </tr>
      {% endfor%}
      </tr>



   </tbody>

</table>
</div>
    <div class="btn-group" style="float: right">
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('jgq.download_jgq') }}" role="button">下载文档</a></p>
    </div>
</div>
{% endblock %}

app/templates/cbfd.html
{% extends "header.html" %}
{% block page_navbar %}
    <div>
    <ul class="nav nav-tabs" role="tablist" id="myTab">
    <li role="presentation" ><a href="/jgq">减刑间隔期计算器</a></li>
    <li role="presentation" class="active"><a href="/cbfd">呈报幅度建议工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑细则速查</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑摸底排查工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">常用问题集</a></li>
    </ul>
    </div>

{% endblock %}

{% block container%}
  <h1>减刑呈报幅度, {{ user }}</h1>
{% endblock %}

app/templates/header.html
{% extends "base.html" %}
{% block navbar%}
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/jgq">哈尔滨监狱减刑辅助工具</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/jgq">主页</a></li>
                <li><a href="#">白天报班</a></li>
                <li><a href="#">夜间报班</a></li>
                <li><a href="#">历史通报</a></li>
                <li><a href="/about">关于</a></li>

            </ul>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

  </div><!-- /.container-fluid -->
</nav>
{% block page_navbar %}
    <div>
    <ul class="nav nav-tabs" role="tablist" id="myTab">
  <li role="presentation" class="active"><a href="/jgq" data-toggle="tab">减刑间隔期计算器</a></li>
  <li role="presentation"><a href="#" data-toggle="tab">呈报幅度建议工具</a></li>
  <li role="presentation"><a href="#" data-toggle="tab">减刑细则速查</a></li>
  <li role="presentation"><a href="#" data-toggle="tab">减刑摸底排查工具</a></li>
  <li role="presentation"><a href="#" data-toggle="tab">常用问题集</a></li>
</ul>
    </div>
{% endblock %}

{% endblock %}

app/templates/index.html
{% extends "header.html" %}
{% block page_navbar %}
    <div>
    <ul class="nav nav-tabs" role="tablist" id="myTab">
    <li role="presentation" class="active"><a href="/jgq">减刑间隔期计算器</a></li>
    <li role="presentation" ><a href="/cbfd">呈报幅度建议工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑细则速查</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑摸底排查工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">常用问题集</a></li>
    </ul>
    </div>

{% endblock %}
{% block container%}

{% endblock %}

app/templates/jgq.html
{% extends "header.html" %}

{% block page_navbar %}
    <div>
    <ul class="nav nav-tabs" role="tablist" id="myTab">
    <li role="presentation" class="active"><a href="/jgq" >减刑间隔期计算器</a></li>
    <li role="presentation" ><a href="/cbfd">呈报幅度建议工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑细则速查</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">减刑摸底排查工具</a></li>
    <li role="presentation"><a href="#" data-toggle="tab">常用问题集</a></li>
    </ul>
    </div>

{% endblock %}


{% block container%}
    <div>
    <h3><span class="label label-primary">方法一：</span></h3>
    <div class="jumbotron">
        <h4>使用说明：</h4>
        <p>输入服刑人员以下基本信息，计算服刑人员呈报减刑间隔期是否符合</p>
    </div>

    <form method="POST" action="/jgq/calc" class="form-horizontal">
    {{ form.hidden_tag() }}
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">罪名：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="zuiming"
                placeholder="请输入罪名">
            </div>
        </div>
            <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">原判刑期：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="yuanpanxingqi"
                placeholder="格式为数字或无期、死缓">
            </div>
        </div>
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">呈报日期：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="chengbaodate"
                placeholder="格式为19990101">
            </div>
        </div>
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">起始时间：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="qishishijian"
                placeholder="格式为19990101">
            </div>
        </div>
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">上次减刑幅度：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="shangcijxfd"
                placeholder="0.6代表减6个月 1代表减1年">
            </div>
        </div>
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">减刑起始时间：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="jxqishishijian"
                placeholder="格式为19990101">
            </div>
        </div>
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">立功：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="ligong"
                placeholder="格式为1代表有，0代表无">
            </div>
        </div>
        <dd>
        <div class="form-group">
            <label for="text" class="col-sm-2 control-label">重大立功：</label>
            <div class="col-sm-2">
            <input type="text" class="form-control" id="text" name="zhongdaligong"
                placeholder="格式为1代表有，0代表无">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-info">计算间隔期</button>
            </div>
        </div>

    </form>
    {% if flag %}
        <h3><div class="alert alert-success" role="alert">{{ str }}</div></h3>
    {% else %}
        <h3><div class="alert alert-danger" role="alert">{{ str }}</div></h3>
    {% endif %}
</div>


    <div>
    <h3><span class="label label-primary">方法二：</span></h3>
    <div class="jumbotron">
        <h4>使用说明：</h4>
        <p>下载表格模板，按要求填写后上传，批量计算服刑人员呈报减刑间隔期是否符合</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('jgq.download_template') }}" role="button">下载表格模板</a></p>
    </div>
        <h4><span class="label label-primary">请选择文件,文件格式为xls、xlsx：</span></h4>
    <form id="form1" method="post" action="/jgq/api/upload" enctype="multipart/form-data">
    <div>
        <input id="File1" type="file" name="myfile"/>
        <button type="submit" class="btn btn-info">提交</button>
    </div>
    </form>
    </div>


    <h3><span class="label label-primary">方法三：</span></h3>
    <div class="jumbotron">
        <h4>使用说明（需连接网威平台数据库）：</h4>
        <p>查询本监区全部服刑人员，批量计算本监区服刑人员呈报减刑间隔期是否符合</p>
    </div>
    </div>
{% endblock %}